
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const BrowseUsers = lazy(() => import("./pages/BrowseUsers.tsx"));
const ProfileEdit = lazy(() => import("./pages/ProfileEdit.tsx"));
const ProfileSetup = lazy(() => import("./pages/ProfileSetup.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <App />},
	{ path: "/browse-users", element: <UserGuard><BrowseUsers /></UserGuard>},
	{ path: "/browseusers", element: <UserGuard><BrowseUsers /></UserGuard>},
	{ path: "/profile-edit", element: <UserGuard><ProfileEdit /></UserGuard>},
	{ path: "/profileedit", element: <UserGuard><ProfileEdit /></UserGuard>},
	{ path: "/profile-setup", element: <UserGuard><ProfileSetup /></UserGuard>},
	{ path: "/profilesetup", element: <UserGuard><ProfileSetup /></UserGuard>},

];
